services:
  api:
    build:
    
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: wcode
    # volumes:
    #     - ../wcode/secrets.json:/app/secrets.json
    # #   - ../django/django-local-efs:/var/www/django-local-efs
    ports:
      - 8000:8000
    networks:
      - wcode
    depends_on:
      - db
  db:
    image: mysql:8.0.36
    container_name: wdb
    volumes:
      - wdb_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - wcode
volumes:
  wdb_data:

networks:
  wcode:
    driver: overlay
    attachable: true