services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile.wsgi
    env_file:
      - .env
    container_name: wsgi
    restart: unless-stopped
    volumes:
          - ./wcode/:/app
    #     - ../wcode/secrets.json:/app/secrets.json
    # #   - ../django/django-local-efs:/var/www/django-local-efs
    ports:
      - 8000:8000
    networks:
      - wcode
    depends_on:
      - postgres
    
  asgi:
    build:
      context: .
      dockerfile: Dockerfile.asgi
    env_file:
      - .env
    container_name: asgi
    restart: unless-stopped
    volumes:
          - ./wcode/:/app
    #     - ../wcode/secrets.json:/app/secrets.json
    # #   - ../django/django-local-efs:/var/www/django-local-efs
    ports:
      - 8001:8001
    networks:
      - wcode
    depends_on:
      - redis

  postgres:
    image: postgres:16.3
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wcode
    
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - wcode

  redis:
    image: redis:7.4.0
    container_name: redis_db
    env_file:
      - .env
    command: >
          --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - wcode

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  wcode:
    driver: overlay
    attachable: true