services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: wcode
    # volumes:
    #     - ../wcode/secrets.json:/app/secrets.json
    # #   - ../django/django-local-efs:/var/www/django-local-efs
    ports:
      - 8000:8000
    networks:
      - wcode
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wcode
    
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - wcode

volumes:
  postgres_data:
  mongo_data:

networks:
  wcode:
    driver: overlay
    attachable: true